-- GENERATED BY MATUGEN - do not edit by hand.
-- Template: ~/.config/matugen/templates/hypr-colors.lua
-- Wallpaper: {{image}}
--
-- Read by hyprland.lua at startup. Without the "#" prefix because Hyprland
-- uses the rgba(RRGGBBAA) format.

return {
    accent  = "{{colors.primary.default.hex_stripped}}",
    accent2 = "{{colors.tertiary.default.hex_stripped}}",
}
