live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "Source Code Pro"

[font.bold_italic]
family = "Source Code Pro"

[font.italic]
family = "Source Code Pro"

[font.normal]
family = "Source Code Pro"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 0.8

[window.padding]
# decoration = "none"
# dynamic_padding = true
x = 20
y = 20
