
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Monitors are matched by description (brand + model + serial), not by
-- connector name (DP-4, HDMI-A-3...). Connector names are assigned by the
-- kernel and they CHANGE across kernels: moving from linux-lts to mainline
-- turned DP-4 into DP-3 and HDMI-A-3 into HDMI-A-1, and every rule below
-- silently stopped applying (goodbye 165 Hz and rotation).
-- The description comes from the monitor EDID, so it is stable.
-- To list them: hyprctl monitors all -j | grep description
MONITOR_MAIN     = "desc:ASR PG32QF2B G5VL0A003533"
MONITOR_VERTICAL = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GS27FA 24476B001914"

-- Main: ASR PG32QF2B 1440p, on the right.
-- Y = 240 centers it vertically against the portrait monitor: (1920 - 1440) / 2
hl.monitor({
    output   = MONITOR_MAIN,
    mode     = "2560x1440@165",
    position = "1080x240",
    scale    = 1,
})

-- Secondary: Gigabyte GS27FA 1080p, rotated to portrait, on the left.
-- transform = 3 -> 270 degrees. If the image comes up upside down, use 1 (90).
-- Rotated it takes 1080x1920, which is why the main one starts at X = 1080.
hl.monitor({
    output    = MONITOR_VERTICAL,
    mode      = "1920x1080@165",
    position  = "0x0",
    scale     = 1,
    transform = 3,
})

-- Fallback for any monitor not listed above
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"

-- Nautilus instead of Dolphin, and the reason is color: Dolphin ignored the
-- wallpaper palette no matter what, because KF6 forced its internal
-- BreezeDark on top of the platform theme. Nautilus is GTK4/libadwaita and
-- reads ~/.config/gtk-4.0/gtk.css, which matugen already generates, so it
-- joins the accent system for free.
--
-- The other file manager is ranger, which lives in the terminal and is
-- started by typing "ranger". Deliberately unbound: when you want it you
-- are already in kitty.
local fileManager = "nautilus"

-- Application launcher. No longer a script: like the power menu, this only
-- flips a property in the running shell, so `qs -d` has to be up for the
-- bind to do anything. See modules/launcher in the quickshell config.

local menu        = "qs ipc call launcher toggle"

-- Power menu with confirmation (SUPER + SHIFT + ESCAPE).
-- No longer a script: the menu is a Quickshell module and this only flips a
-- property in the running shell. See modules/powermenu in the quickshell
-- config. `toggle` and not `open`, so the same shortcut puts it away.
local powerMenu   = "qs ipc call powermenu toggle"


-------------------------------
---- WALLPAPER COLOR SCHEME ----
-------------------------------

-- Absolute path. Not strictly required any more (the ENVIRONMENT VARIABLES
-- section adds ~/.local/bin to PATH), but kept because autostart runs at a
-- delicate point of the boot and this must not fail. Newer scripts can be
-- called by name.
local wallpaperSwitch = os.getenv("HOME") .. "/.local/bin/wallpaper-switch"

-- colors.lua is generated by matugen every time the wallpaper changes.
-- If it does not exist yet (first boot, or matugen failed) the original
-- colors are used, so the config never breaks.
local wallColors = { accent = "33ccff", accent2 = "00ff99" }

local ok, generated = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
if ok and type(generated) == "table" and generated.accent and generated.accent2 then
    wallColors = generated
end


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("qs -d & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Without this, systemd --user services (such as wallpaper-rotate.timer)
    -- cannot see WAYLAND_DISPLAY or the Hyprland signature, and cannot talk
    -- to the compositor. It has to come first.
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")

    -- The shell: bar, island, notifications, launcher and power menu.
    -- Config in ~/.config/quickshell/.
    --
    -- --no-duplicate makes a second invocation exit instead of stacking a
    -- second copy of every layer surface, which is what happens when this
    -- line and a manual `qs -d` both run.
    hl.exec_cmd("qs -d --no-duplicate")

    -- No notification daemon is started here any more. Quickshell IS the
    -- daemon: it takes org.freedesktop.Notifications itself, and two processes
    -- cannot own one bus name -- whichever asks second simply does not get it.
    -- dunst is gone; see modules/notifications in the quickshell config.
    --
    -- mpris-notify went with it. It sent its track notifications with
    -- `dunstify`, a binary the dunst package owns, so it could not survive the
    -- removal -- and it had already stopped doing anything visible before
    -- that: the shell drops notifications from "mpris-notify" on purpose, and
    -- what is playing now lives in the island in the centre of the bar. The
    -- script is still in ~/.local/bin if it is ever wanted back.

    -- Wallpaper daemon + restore the last one used
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(wallpaperSwitch .. " reapply")

    -- On Wayland the clipboard is not stored anywhere central: it is owned
    -- by the source application. Close it and whatever you copied is gone.
    -- wl-clip-persist takes ownership so it survives.
    -- Only "regular": also handling the primary selection fights with
    -- middle-click and causes rewrite loops.
    hl.exec_cmd("wl-clip-persist --clipboard regular")

    -- Clipboard history. Two watchers are needed because wl-paste --watch
    -- filters by MIME type and a single one would leave images out
    -- (screenshots from SUPER+S among them).
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Without this, Qt apps come up with the factory grey palette: there is no
-- "system Qt theme" to detect under Hyprland, it has to be named. Points at
-- qt6ct, whose palette matugen generates from the wallpaper
-- (~/.config/qt6ct/colors/matugen.conf).
--
-- CAREFUL: it is ONE variable for every Qt version, and here it only serves
-- Qt6. A Qt5 app would look for a plugin called "qt6ct" in ITS own directory
-- (/usr/lib/qt/plugins/platformthemes/), fail to find it and fall back to the
-- default theme: grey palette, plus default font metrics that bloat its
-- tooltips and menus.
--
-- Fixing a Qt5 app would need qt5ct and a dedicated .desktop overriding the
-- variable for that app alone. Check the version first with
-- `ldd $(which the-app) | grep libQt`.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Hyprland starts with a minimal PATH that does not include ~/.local/bin, so
-- any own script invoked by name fails silently. Evaluated when the config
-- loads, taking the compositor's real PATH.
hl.env("PATH", os.getenv("HOME") .. "/.local/bin:" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin"))

-- Without this, the "Open with" dialog of KDE apps comes up empty. KService
-- builds its application tree from
-- /etc/xdg/menus/$XDG_MENU_PREFIX + applications.menu. Hyprland sets the
-- prefix to "hyprland-", but nobody creates that file: the classic
-- applications.menu shipped with Plasma, which is not installed here.
-- archlinux-xdg-menu installs arch-applications.menu, so the prefix has to
-- point there.
--
-- CAREFUL: after changing this the cache must be rebuilt with
-- `kbuildsycoca6 --noincremental`; hyprctl reload is not enough.
hl.env("XDG_MENU_PREFIX", "arch-")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border = {
                colors = {
                    "rgba(" .. wallColors.accent  .. "ee)",
                    "rgba(" .. wallColors.accent2 .. "ee)",
                },
                angle = 45,
            },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        -- 10, and this one is set from the OUTSIDE in. Applications draw
        -- their own rounded corner for the content inside the window, and at
        -- 24 the compositor's curve was visibly rounder than the app's, so
        -- every window showed two disagreeing arcs nested in one another.
        -- Measured on Zen's content area (grim over the window, first light
        -- pixel per row, from y=8 x=200 to y=17 x=191): the curve spans
        -- ~10 px. So this is not a taste setting, it is the radius the
        -- applications already use.
        --
        -- Quickshell uses the same figure for the rounded screen corners and
        -- for the fillet where the bar meets the sides (Theme.qml:
        -- screenCornerRadius / barCornerRadius). Those three are one
        -- decision, not three: they are the radii that touch each other on
        -- screen. Change all three together or the edges stop agreeing.
        --
        -- What this costs, because the history below is real and going back
        -- down is not free: a concave fillet has only as many pixel rows as
        -- its radius to spread its antialiasing over, so the bar fillet at
        -- 10 shades more coarsely than at 24. That is the price paid to kill
        -- the double arc on every window. If the fillet ever reads jagged,
        -- this is why, and the fix is a bigger radius in all three places.
        --
        -- History: 10 -> 16 (to line up with Quickshell) -> 24 (to settle
        -- the jagged fillets) -> 10 (to match the applications).
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        -- "Glass" effect: Hyprland applies the blur behind any transparent
        -- window (kitty runs at background_opacity 0.70).
        --
        --   size   = blur radius. Higher = softer.
        --   passes = how many times it repeats. This is what turns a faint
        --            veil into actual frosted glass. Beyond 4 it is barely
        --            noticeable and costs GPU.
        blur = {
            enabled = true,

            -- 14, up from 8, for a frostier glass behind Zen's sidebar.
            -- `size` is the only lever available for that: `passes` is
            -- pinned at 2 for edge quality (measured, see below), so making
            -- the backdrop softer has to come from the radius.
            --
            -- CAREFUL, this is GLOBAL. It is not a browser setting: every
            -- translucent surface gets it -- kitty at background_opacity
            -- 0.70, the Quickshell bar, the notification panel, popups. It
            -- was raised alongside Zen's own tint going 0.72 -> 0.85
            -- (userChrome.css, --zen-background-opacity), which is the pair
            -- that produces "glass" rather than "see-through": more blur
            -- behind, less wallpaper coming through the tint. If the
            -- terminal ever looks mushy behind its text, this is the number.
            size    = 14,

            -- 2 AND NOT 3, and the reason is edge quality rather than taste.
            --
            -- Each pass halves the resolution the blur is computed at, so at
            -- 3 the backdrop is sampled 8x coarser than the screen. Where a
            -- shell surface has an ANTIALIASED curved edge, its partially
            -- transparent pixels blend with that coarse backdrop, and the
            -- gradient that makes the curve look smooth turns into steps --
            -- the jagged corners that took a whole session to pin down.
            --
            -- Measured on the notification panel's bottom-right corner over a
            -- bright window, in intermediate pixels per row (more is
            -- smoother): passes 3 -> 1.58, passes 1 -> 3.00, passes 2 -> 4.04,
            -- which equals turning the blur off entirely. So 2 costs nothing
            -- visually and fixes the edges.
            passes  = 2,

            -- Subtle grain: breaks the banding (colour stepping) that blur
            -- leaves over wallpaper gradients.
            noise = 0.0117,

            -- Darkens and lowers the contrast of what is behind, so the
            -- terminal's light text stays readable over bright wallpapers.
            contrast   = 0.9,
            brightness = 0.8,

            -- Saturates the colours of the blurred background (macOS style).
            vibrancy          = 0.1696,
            vibrancy_darkness = 0.0,

            -- Blur context menus and popups too.
            popups       = true,
            popups_ignorealpha = 0.2,

            -- xray = true blurs only the wallpaper, ignoring the windows
            -- underneath. Cleaner and cheaper, but you lose the sense of
            -- stacked layers. Try it if your GPU struggles with passes = 3.
            xray = false,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
-- Horizontal slide when switching workspace. Other possible styles:
-- "slidevert" (vertical), "slidefade 20%" (slide and fade), "fade".
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal), { description = "Apps: open a terminal" })
local closeWindowBind = hl.bind(mainMod .. " + W", hl.dsp.window.close(), { description = "Windows: close the focused window" })
-- closeWindowBind:set_enabled(false)
-- Power menu (log out / restart / shut down) with confirmation.
-- This used to be SUPER + M with no protection at all and it ended the
-- session instantly; far too easy to hit by accident. Now it takes
-- SHIFT + ESCAPE and you still have to pick from the menu, where nothing is
-- preselected and a click anywhere outside dismisses it.
--
-- If nothing happens, the shell is not running: the menu lives inside
-- Quickshell now, so `qs -d` has to be up for this bind to do anything.
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd(powerMenu), { description = "Shell: power menu" })

-- SUPER + M was deliberately free for a while; now the magic special
-- workspace lives there, after giving up S to screenshots.
-- The island's dashboard. Same call the click on the island makes, so the
-- key and the pointer cannot drift apart. D for dashboard; it was free.
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("qs ipc call island dashboard"), { description = "Shell: open the dashboard" })

-- Do not disturb. N for notifications; it was free.
--
-- A key and not only the switch in the dashboard, because the moment it is
-- wanted is the moment a game or a call has already started -- which is
-- exactly when opening a panel to reach a toggle is what you cannot do.
-- Turning it on is silent by design; the badge beside the island is how it
-- stays visible afterwards.
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("qs ipc call dnd toggle"), { description = "Shell: mute notifications (do not disturb)" })

-- ...and the other half: what came in while it was muted, or while you were
-- not at the desk. Same key with SHIFT, because it is the same subject.
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("qs ipc call island notifications"), { description = "Shell: notification history" })

-- The cheatsheet: every bind that carries a description, laid out by category.
--
-- It reads `hyprctl binds` rather than this file, so the two cannot drift: the
-- compositor is the one that knows what is actually bound right now. The only
-- thing a new bind needs in order to show up is a description, in the
-- "Category: what it does" form used throughout the section below. A bind with
-- no description is deliberately invisible there.
--
-- SUPER + / because ? is the help key everywhere and / is where it lives
-- unshifted. It was free, and it is the only bind whose job is to explain the
-- others, so it belongs to the shell rather than to any category.
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("qs ipc call cheatsheet toggle"), { description = "Shell: this cheatsheet" })

hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), { description = "Apps: open the file manager" })
-- Toggle floating. It used to be SUPER+V, Hyprland's example bind, but that
-- key went to the clipboard history: V for "paste" is used far more often
-- than floating a window. T comes from togglefloating, the real dispatcher
-- name.
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }), { description = "Windows: float or tile" })
-- Pin: the window stays visible on every workspace of ITS monitor, in the
-- same position. SHIFT + T for continuity with the float bind above.
-- CAREFUL: pin only acts on floating windows, so the order is SUPER+T and
-- then SUPER+SHIFT+T. And it is per monitor: it does not cross over.
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.pin(), { description = "Windows: pin a floating window to every workspace" })
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu), { description = "Apps: open the launcher" })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo(), { description = "Windows: pseudotile" })
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), { description = "Windows: flip the split direction" })  -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { description = "Windows: move focus left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "Windows: move focus right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { description = "Windows: move focus up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { description = "Windows: move focus down" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
--
-- Only the FIRST of each ten carries a description, and that is what keeps the
-- cheatsheet readable: it lists every bind that has one, so describing all
-- twenty would spend two thirds of a column saying the same thing ten times.
-- The row shows SUPER + 1 and the text names the range.
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    local focusOpts = i == 1 and { description = "Workspaces: go to workspace 1-10" } or nil
    local moveOpts  = i == 1 and { description = "Workspaces: send the window to workspace 1-10" } or nil
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}), focusOpts)
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }), moveOpts)
end

-- Special workspace (scratchpad). It lived on SUPER+S, but that key was
-- handed over entirely to screenshots, which are used far more often and
-- where SUPER+SHIFT+S is the gesture everyone already has in their fingers.
-- M was reserved and unused, so it moved here.
hl.bind(mainMod .. " + M",         hl.dsp.workspace.toggle_special("magic"), { description = "Workspaces: show or hide the magic scratchpad" })
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:magic" }), { description = "Workspaces: send the window to the scratchpad" })

-- Wallpapers: SUPER+SHIFT+W goes to the next one, SUPER+SHIFT+A picks at
-- random. Each change regenerates the accent palette (the shell, kitty,
-- window borders).
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(wallpaperSwitch .. " next"), { description = "Look: next wallpaper" })
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(wallpaperSwitch .. " random"), { description = "Look: random wallpaper" })

-- Screenshots: hyprshot (a wrapper over grim/slurp that also asks hyprctl
-- for window and monitor geometry) plus satty for annotating. The whole
-- SUPER+S family is for this; the magic special workspace moved to SUPER+M
-- to free it up.
--
-- -z freezes the image while you select the region. Without it you cannot
-- capture dropdown menus or tooltips: they vanish as soon as you move the
-- mouse to drag the selection. Requires hyprpicker.
--
-- Plain SUPER+S only copies to the clipboard and never touches disk, which
-- is the common case (paste into the browser or Discord). The variants that
-- do write a file go to ~/Pictures via XDG_PICTURES_DIR.
-- satty expands strftime patterns in the output name, so no shell $(date)
-- is needed and there is nothing to escape.
local sattyPipe = "satty --filename - --copy-command wl-copy --early-exit"
    .. " --output-filename " .. os.getenv("HOME") .. "/Pictures/satty-%Y%m%d-%H%M%S.png"

hl.bind(mainMod .. " + S",         hl.dsp.exec_cmd("hyprshot -m region -z --clipboard-only"), { description = "Capture: region to the clipboard" })
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region -z --raw | " .. sattyPipe), { description = "Capture: region, then annotate it" })
-- hyprshot modes combine: plain "window" and "output" open a picker to click
-- the window or the monitor, which is pointless here. Adding "active" makes
-- them take the focused window or the monitor under the pointer directly,
-- with no interaction. That is also why they do not carry -z.
hl.bind(mainMod .. " + CTRL + S",  hl.dsp.exec_cmd("hyprshot -m window -m active"), { description = "Capture: the focused window to a file" })
hl.bind(mainMod .. " + ALT + S",   hl.dsp.exec_cmd("hyprshot -m output -m active"), { description = "Capture: the whole monitor to a file" })

-- Instant replay. The shell keeps the last 30 seconds of the main monitor in
-- RAM at all times (see modules/recorder/ReplayState.qml), so this writes the
-- past rather than starting anything: by the time you know you want the clip,
-- the moment is already over, which is the entire reason the buffer is armed
-- from boot.
--
-- ALT + Z, with no SUPER, because it is pressed in the middle of whatever was
-- worth keeping -- and that is also the one caveat: a global bind on a plain
-- ALT combination takes ALT+Z away from every application that wanted it.
hl.bind("ALT + Z", hl.dsp.exec_cmd("qs ipc call replay save"), { description = "Capture: save the last 30 seconds" })

-- Clipboard history. It opens the shell's launcher straight into its
-- clipboard picker instead of a dmenu: images are shown as images there,
-- which a text menu could never do -- cliphist only reports binary entries as
-- a description like "[[ binary data 7 KiB png 234x119 ]]".
--
-- cliphist itself stays: it is the store, and the two `wl-paste --watch`
-- processes above keep filling it. Only the picking moved.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("qs ipc call launcher clipboard"), { description = "Apps: clipboard history" })

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Workspaces: next existing workspace" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Workspaces: previous existing workspace" })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true, description = "Windows: drag to move" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Windows: drag to resize" })

-- Multimedia keys for volume and LCD brightness.
--
-- NO DESCRIPTIONS, so none of these reach the cheatsheet. A dedicated key
-- carries its own function printed on the keycap: a row saying that the volume
-- key changes the volume is one you would never go looking for, and seven of
-- them cost a whole column of a sheet whose job is the chords you cannot see.
-- -l 1.5 allows boosting up to 150%
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)


-- Blur for the Quickshell bar under trial on the portrait monitor.
-- Its namespace is set in QML, not by the process name: see
-- WlrLayershell.namespace in ~/.config/quickshell/modules/bar/Bar.qml.
-- Remove this rule together with the quickshell stow package if the trial
-- does not end in a migration.
hl.layer_rule({
    name  = "blur-quickshell",
    -- The popouts, the notification panel and the power menu share the bar's
    -- glass, so they share its blur. Screen corners are opaque black and
    -- deliberately left out.
    --
    -- Anything quickshell puts on screen with a glass surface has to be named
    -- here. A namespace that is NOT matched does not come out unblurred -- it
    -- falls through to the GLOBAL decoration.blur, which has different
    -- parameters and no xray, and the surface ends up visibly blurrier than
    -- the bar it is supposed to belong to. That is how the power menu looked
    -- before it was added to this list.
    match = { namespace = "^quickshell-(bar|popout|notifications|powermenu|launcher|cheatsheet)$" },

    blur          = true,

    -- 0.84: JUST UNDER the surfaces' own alpha (Theme.glassAlpha = 0.85).
    -- These two numbers are tied; move one and move the other.
    --
    -- Hyprland blurs the WHOLE rectangle of a layer surface. It has no idea
    -- the shell drew a rounded corner inside it, so the blur carries on into
    -- the transparent area outside the curve and juts out past the edge --
    -- the sawtooth sticking out beyond the border. ignore_alpha is what
    -- excludes pixels from the blur: at 0 (what was here) nothing is
    -- excluded and the whole corner bleeds; just below the fill's alpha, only
    -- the solid interior gets blurred and the antialiased edge is left alone.
    --
    -- It is not enough on its own: with passes at 3 the corner steps again
    -- whatever this is set to. Both changes are needed.
    ignore_alpha  = 0.84,
    blur_popups   = true,

    -- xray makes the blur sample ONLY the wallpaper, ignoring the windows in
    -- between. Without it the bar and its popouts are the same colour in the
    -- config and different colours on screen: the bar sits over the
    -- wallpaper, a popout hangs over whatever window is below it, and a
    -- surface at 85% opacity shows what is behind it. Measured: bar
    -- rgb(39,44,37) against popout rgb(25,28,25). With xray both composite
    -- over the same wallpaper and match.
    xray = true,
})


-- The blur-dunst rule was here. It matched the namespace "notifications",
-- which was dunst's layer; Quickshell's panel calls itself
-- "quickshell-notifications" and is covered by blur-quickshell above.
-- Nothing on this system creates a bare "notifications" layer any more.

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Helper apps kept out of the tiling: they are opened briefly and closed,
-- and tiled they would reshuffle the rest of the workspace on every launch.
--
-- The classes are the ones reported by `hyprctl clients`, NOT the
-- StartupWMClass from the .desktop: the two do not always match.

-- Nautilus, the graphical file manager (SUPER + E).
--
-- Transparency is the only part of the look that does NOT come from GTK:
-- libadwaita paints its background opaque and there is no way to ask it for
-- an alpha from user CSS, so the compositor provides it. The blur does not
-- need declaring -- decoration.blur is already globally enabled and Hyprland
-- applies it behind any translucent window, same as with kitty.
--
-- CAREFUL: opacity affects the WHOLE window, text and icons included.
-- 0.82 is the point where the glass reads without file names fighting the
-- wallpaper. Go lower and label text starts losing contrast over images with
-- bright detail; the blur already ships with brightness 0.8 to compensate,
-- but there is a limit.
--
-- And CAREFUL with the SYNTAX, which here is not what you would expect from
-- a Lua config: opacity is a TEXT field with hyprlang grammar --
-- "active inactive fullscreen", the last two optional. There is no
-- opacity_inactive field, a bare number per state is not accepted, and
-- neither is a table { active =, inactive = }: the parser rejects all three
-- with "field 'opacity': string type requires a string".
--
-- Worse: `hyprctl reload` answers "ok" anyway and the rule is silently
-- dropped. The error only shows through `hyprctl configerrors` and in the
-- red banner in the corner. If you touch this, check with configerrors, not
-- with the exit code.
hl.window_rule({
    name  = "float-nautilus",
    match = { class = "^org\\.gnome\\.Nautilus$" },

    float  = true,
    size   = "1400 850",
    center = true,

    -- Both values identical, and that is the point: the second one is the
    -- INACTIVE opacity, and at 0.74 the window visibly changed colour the
    -- moment it lost focus. Worse than a uniform dim: the sidebar and the
    -- content pane are different widgets sitting over different parts of
    -- the blurred wallpaper, so the same drop in alpha moved them by
    -- different amounts and the chrome stopped matching itself.
    -- The GTK side of this is in the gtk4-colors.css template, where every
    -- *_backdrop_color equals its bg colour for the same reason. Changing
    -- one without the other brings the mismatch back.
    opacity = "0.82 0.82",
})

-- Loupe (images) and Celluloid (video) replaced gwenview and haruna. The
-- reason was the same one that pushed out Dolphin: both linked
-- libKF6ColorScheme, which forces BreezeDark on the app over the platform
-- theme, so they stayed grey while the rest of the desktop followed the
-- wallpaper.
--
-- Both are GTK4/libadwaita, meaning they read ~/.config/gtk-4.0/gtk.css just
-- like Nautilus and need no new template.
--
-- NO opacity here, unlike Nautilus, and that is deliberate: opacity in
-- Hyprland affects the whole window, content included. In an image viewer
-- and a media player that means blending the wallpaper into the picture you
-- are looking at -- goodbye blacks and any colour judgement. The glass is
-- for the chrome, not for the content.
hl.window_rule({
    name  = "float-loupe",
    match = { class = "^org\\.gnome\\.Loupe$" },

    float  = true,
    size   = "1400 850",
    center = true,
})

hl.window_rule({
    name  = "float-celluloid",
    match = { class = "^io\\.github\\.celluloid_player\\.Celluloid$" },

    float  = true,
    size   = "1280 720",   -- 16:9, so it does not come up letterboxed
    center = true,
})

-- zathura, the PDF reader.
--
-- Fixed "size" with A4 portrait proportions (850/1180 = 0.72, A4 is 0.707).
-- Measured: zathura does NOT request a size matching the document. With an
-- A4 portrait (ratio 0.71) it opens at 1252x952 and with a landscape one
-- (1.41) at 804x617 -- both windows land at ratio ~1.30, unrelated to the
-- page. So without a fixed size you get a landscape window for a portrait
-- document and wasted background on the sides.
--
-- Hyprland cannot measure the content either: it only sees what the window
-- asks for. Fitting it properly would need reading the page dimensions with
-- pdfinfo before opening and resizing afterwards.
--
-- 1180 of height fits DP-3 (1440) leaving room for the bar.
hl.window_rule({
    name  = "float-zathura",
    match = { class = "^org\\.pwmt\\.zathura$" },

    float  = true,
    size   = "850 1180",
    center = true,
})

-- satty, the annotation editor that SUPER+SHIFT+S pipes the screenshot into
-- (see the screenshot section above).
--
-- No "size" on purpose: the window fits the screenshot, and forcing a fixed
-- measure would distort the canvas depending on whether you grabbed a small
-- region or a whole monitor.
--
-- But "max_size" IS needed: satty asks for a window the size of the image,
-- so capturing a whole monitor (or opening a large image) pushes it off
-- screen and the buttons at the bottom end up out of reach. The cap fits
-- DP-3 leaving room for the bar.
hl.window_rule({
    name  = "float-satty",
    match = { class = "^com\\.gabm\\.satty$" },

    float    = true,
    max_size = "2400 1300",
    center   = true,
})


---------------
---- GAMING ----
---------------
-- Render, environment and window rules for games.
-- See ~/.config/hypr/gaming.lua
require("gaming")
