
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Monitors are matched by description (brand + model + serial), not by
-- connector name (DP-4, HDMI-A-3...). Connector names are assigned by the
-- kernel and they CHANGE across kernels: moving from linux-lts to mainline
-- turned DP-4 into DP-3 and HDMI-A-3 into HDMI-A-1, and every rule below
-- silently stopped applying (goodbye 165 Hz and rotation).
-- The description comes from the monitor EDID, so it is stable.
-- To list them: hyprctl monitors all -j | grep description
MONITOR_MAIN     = "desc:ASR PG32QF2B G5VL0A003533"
MONITOR_VERTICAL = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GS27FA 24476B001914"

-- Main: ASR PG32QF2B 1440p, on the right.
-- Y = 240 centers it vertically against the portrait monitor: (1920 - 1440) / 2
hl.monitor({
    output   = MONITOR_MAIN,
    mode     = "2560x1440@165",
    position = "1080x240",
    scale    = 1,
})

-- Secondary: Gigabyte GS27FA 1080p, rotated to portrait, on the left.
-- transform = 3 -> 270 degrees. If the image comes up upside down, use 1 (90).
-- Rotated it takes 1080x1920, which is why the main one starts at X = 1080.
hl.monitor({
    output    = MONITOR_VERTICAL,
    mode      = "1920x1080@165",
    position  = "0x0",
    scale     = 1,
    transform = 3,
})

-- Fallback for any monitor not listed above
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"

-- Nautilus instead of Dolphin, and the reason is color: Dolphin ignored the
-- wallpaper palette no matter what, because KF6 forced its internal
-- BreezeDark on top of the platform theme. Nautilus is GTK4/libadwaita and
-- reads ~/.config/gtk-4.0/gtk.css, which matugen already generates, so it
-- joins the accent system for free.
--
-- The other file manager is ranger, which lives in the terminal and is
-- started by typing "ranger". Deliberately unbound: when you want it you
-- are already in kitty.
local fileManager = "nautilus"

-- Grid launcher with a glass background. It is a script rather than plain
-- "wofi --show drun" because it needs XDG_CONFIG_HOME pointing at an empty
-- directory, or the user gtk.css forces an opaque background on it.
local menu        = os.getenv("HOME") .. "/.local/bin/wofi-drun"

-- Power menu with confirmation (SUPER + SHIFT + ESCAPE).
-- Absolute path for consistency with wallpaperSwitch.
local powerMenu   = os.getenv("HOME") .. "/.local/bin/hypr-powermenu"


-------------------------------
---- WALLPAPER COLOR SCHEME ----
-------------------------------

-- Absolute path. Not strictly required any more (the ENVIRONMENT VARIABLES
-- section adds ~/.local/bin to PATH), but kept because autostart runs at a
-- delicate point of the boot and this must not fail. Newer scripts can be
-- called by name.
local wallpaperSwitch = os.getenv("HOME") .. "/.local/bin/wallpaper-switch"

-- colors.lua is generated by matugen every time the wallpaper changes.
-- If it does not exist yet (first boot, or matugen failed) the original
-- colors are used, so the config never breaks.
local wallColors = { accent = "33ccff", accent2 = "00ff99" }

local ok, generated = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
if ok and type(generated) == "table" and generated.accent and generated.accent2 then
    wallColors = generated
end


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Without this, systemd --user services (such as wallpaper-rotate.timer)
    -- cannot see WAYLAND_DISPLAY or the Hyprland signature, and cannot talk
    -- to the compositor. It has to come first.
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")

    -- Status bar. Config in ~/.config/waybar/
    hl.exec_cmd("waybar")

    -- Notification daemon
    hl.exec_cmd("dunst")

    -- Wallpaper daemon + restore the last one used
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(wallpaperSwitch .. " reapply")

    -- Notification with cover art when the browser changes track (YouTube,
    -- YouTube Music). Deliberately after dunst: if the notification daemon
    -- is not up yet, the first track is lost.
    -- See ~/.local/bin/mpris-notify.
    hl.exec_cmd("mpris-notify")

    -- On Wayland the clipboard is not stored anywhere central: it is owned
    -- by the source application. Close it and whatever you copied is gone.
    -- wl-clip-persist takes ownership so it survives.
    -- Only "regular": also handling the primary selection fights with
    -- middle-click and causes rewrite loops.
    hl.exec_cmd("wl-clip-persist --clipboard regular")

    -- Clipboard history. Two watchers are needed because wl-paste --watch
    -- filters by MIME type and a single one would leave images out
    -- (screenshots from SUPER+S among them).
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Without this, Qt apps come up with the factory grey palette: there is no
-- "system Qt theme" to detect under Hyprland, it has to be named. Points at
-- qt6ct, whose palette matugen generates from the wallpaper
-- (~/.config/qt6ct/colors/matugen.conf).
--
-- CAREFUL: it is ONE variable for every Qt version, and here it only serves
-- Qt6. A Qt5 app would look for a plugin called "qt6ct" in ITS own directory
-- (/usr/lib/qt/plugins/platformthemes/), fail to find it and fall back to the
-- default theme: grey palette, plus default font metrics that bloat its
-- tooltips and menus.
--
-- Fixing a Qt5 app would need qt5ct and a dedicated .desktop overriding the
-- variable for that app alone. Check the version first with
-- `ldd $(which the-app) | grep libQt`.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Hyprland starts with a minimal PATH that does not include ~/.local/bin, so
-- any own script invoked by name fails silently. Evaluated when the config
-- loads, taking the compositor's real PATH.
hl.env("PATH", os.getenv("HOME") .. "/.local/bin:" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin"))

-- Without this, the "Open with" dialog of KDE apps comes up empty. KService
-- builds its application tree from
-- /etc/xdg/menus/$XDG_MENU_PREFIX + applications.menu. Hyprland sets the
-- prefix to "hyprland-", but nobody creates that file: the classic
-- applications.menu shipped with Plasma, which is not installed here.
-- archlinux-xdg-menu installs arch-applications.menu, so the prefix has to
-- point there.
--
-- CAREFUL: after changing this the cache must be rebuilt with
-- `kbuildsycoca6 --noincremental`; hyprctl reload is not enough.
hl.env("XDG_MENU_PREFIX", "arch-")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border = {
                colors = {
                    "rgba(" .. wallColors.accent  .. "ee)",
                    "rgba(" .. wallColors.accent2 .. "ee)",
                },
                angle = 45,
            },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        -- "Glass" effect: Hyprland applies the blur behind any transparent
        -- window (kitty runs at background_opacity 0.70).
        --
        --   size   = blur radius. Higher = softer.
        --   passes = how many times it repeats. This is what turns a faint
        --            veil into actual frosted glass. Beyond 4 it is barely
        --            noticeable and costs GPU.
        blur = {
            enabled = true,
            size    = 8,
            passes  = 3,

            -- Subtle grain: breaks the banding (colour stepping) that blur
            -- leaves over wallpaper gradients.
            noise = 0.0117,

            -- Darkens and lowers the contrast of what is behind, so the
            -- terminal's light text stays readable over bright wallpapers.
            contrast   = 0.9,
            brightness = 0.8,

            -- Saturates the colours of the blurred background (macOS style).
            vibrancy          = 0.1696,
            vibrancy_darkness = 0.0,

            -- Blur context menus and popups too.
            popups       = true,
            popups_ignorealpha = 0.2,

            -- xray = true blurs only the wallpaper, ignoring the windows
            -- underneath. Cleaner and cheaper, but you lose the sense of
            -- stacked layers. Try it if your GPU struggles with passes = 3.
            xray = false,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
-- Horizontal slide when switching workspace. Other possible styles:
-- "slidevert" (vertical), "slidefade 20%" (slide and fade), "fade".
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + W", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
-- Power menu (log out / restart / shut down) with confirmation.
-- This used to be SUPER + M with no protection at all and it ended the
-- session instantly; far too easy to hit by accident. Now it takes
-- SHIFT + ESCAPE and you still have to pick from the menu, where "Cancel"
-- comes preselected. The script lives in ~/.local/bin/hypr-powermenu.
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd(powerMenu))

-- SUPER + M was deliberately free for a while; now the magic special
-- workspace lives there, after giving up S to screenshots.
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
-- Toggle floating. It used to be SUPER+V, Hyprland's example bind, but that
-- key went to the clipboard history: V for "paste" is used far more often
-- than floating a window. T comes from togglefloating, the real dispatcher
-- name.
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
-- Pin: the window stays visible on every workspace of ITS monitor, in the
-- same position. SHIFT + T for continuity with the float bind above.
-- CAREFUL: pin only acts on floating windows, so the order is SUPER+T and
-- then SUPER+SHIFT+T. And it is per monitor: it does not cross over.
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.pin())
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad). It lived on SUPER+S, but that key was
-- handed over entirely to screenshots, which are used far more often and
-- where SUPER+SHIFT+S is the gesture everyone already has in their fingers.
-- M was reserved and unused, so it moved here.
hl.bind(mainMod .. " + M",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:magic" }))

-- Wallpapers: SUPER+SHIFT+W goes to the next one, SUPER+SHIFT+A picks at
-- random. Each change regenerates the accent palette (waybar, kitty,
-- borders, dunst).
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(wallpaperSwitch .. " next"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(wallpaperSwitch .. " random"))

-- Screenshots: hyprshot (a wrapper over grim/slurp that also asks hyprctl
-- for window and monitor geometry) plus satty for annotating. The whole
-- SUPER+S family is for this; the magic special workspace moved to SUPER+M
-- to free it up.
--
-- -z freezes the image while you select the region. Without it you cannot
-- capture dropdown menus or tooltips: they vanish as soon as you move the
-- mouse to drag the selection. Requires hyprpicker.
--
-- Plain SUPER+S only copies to the clipboard and never touches disk, which
-- is the common case (paste into the browser or Discord). The variants that
-- do write a file go to ~/Pictures via XDG_PICTURES_DIR.
-- satty expands strftime patterns in the output name, so no shell $(date)
-- is needed and there is nothing to escape.
local sattyPipe = "satty --filename - --copy-command wl-copy --early-exit"
    .. " --output-filename " .. os.getenv("HOME") .. "/Pictures/satty-%Y%m%d-%H%M%S.png"

hl.bind(mainMod .. " + S",         hl.dsp.exec_cmd("hyprshot -m region -z --clipboard-only"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region -z --raw | " .. sattyPipe))
-- hyprshot modes combine: plain "window" and "output" open a picker to click
-- the window or the monitor, which is pointless here. Adding "active" makes
-- them take the focused window or the monitor under the pointer directly,
-- with no interaction. That is also why they do not carry -z.
hl.bind(mainMod .. " + CTRL + S",  hl.dsp.exec_cmd("hyprshot -m window -m active"))
hl.bind(mainMod .. " + ALT + S",   hl.dsp.exec_cmd("hyprshot -m output -m active"))

-- Clipboard history (cliphist), reusing wofi in dmenu mode. It keeps plain
-- SUPER+V for proximity with the usual Ctrl+V; the float toggle that used to
-- live here moved to SUPER+T.
--
-- "decode" is essential: cliphist list emits a numeric id and a truncated
-- preview, not the content. Without decode you would paste the summary.
-- To empty it: cliphist wipe
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(
    "cliphist list | wofi --dmenu --prompt Clipboard | cliphist decode | wl-copy"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
-- -l 1.5 allows boosting up to 150% (same as max-volume in waybar)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Blur for waybar: the bar is semi-transparent in CSS, but the actual blur
-- is applied by Hyprland on the layer.
-- CAREFUL: the layer namespace is the "name" field of each bar in
-- config.jsonc (not "waybar"). If you rename a bar, update this.
hl.layer_rule({
    name  = "blur-waybar",
    match = { namespace = "^(main|vertical)$" },

    blur          = true,
    ignore_alpha  = 0.2,

    -- Bar tooltips (the panel that appears when hovering a module) are
    -- popups of this layer, not layers of their own. Without this they end
    -- up semi-transparent but NOT blurred, which is exactly what reads as
    -- "see-through" instead of "glass".
    blur_popups = true,
})

-- Blur for wofi (SUPER + SPACE and SUPER + SHIFT + ESCAPE). Same case as
-- waybar: the semi-transparent background comes from the stylesheet, the
-- blur goes here. The wofi layer namespace is literally "wofi".
hl.layer_rule({
    name  = "blur-wofi",
    match = { namespace = "^wofi$" },

    blur          = true,
    ignore_alpha  = 0.2,
    blur_popups   = true,
})

-- Blur for dunst notifications. Its layer namespace is "notifications"
-- (not "dunst"), as reported by `hyprctl layers`.
-- The base transparency is defined in ~/.config/matugen/templates/dunstrc.
hl.layer_rule({
    name  = "blur-dunst",
    match = { namespace = "^notifications$" },

    blur          = true,
    ignore_alpha  = 0.2,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Helper apps kept out of the tiling: they are opened briefly and closed,
-- and tiled they would reshuffle the rest of the workspace on every launch.
--
-- The classes are the ones reported by `hyprctl clients`, NOT the
-- StartupWMClass from the .desktop: the two do not always match.

-- Nautilus, the graphical file manager (SUPER + E).
--
-- Transparency is the only part of the look that does NOT come from GTK:
-- libadwaita paints its background opaque and there is no way to ask it for
-- an alpha from user CSS, so the compositor provides it. The blur does not
-- need declaring -- decoration.blur is already globally enabled and Hyprland
-- applies it behind any translucent window, same as with kitty.
--
-- CAREFUL: opacity affects the WHOLE window, text and icons included.
-- 0.82 is the point where the glass reads without file names fighting the
-- wallpaper. Go lower and label text starts losing contrast over images with
-- bright detail; the blur already ships with brightness 0.8 to compensate,
-- but there is a limit.
--
-- And CAREFUL with the SYNTAX, which here is not what you would expect from
-- a Lua config: opacity is a TEXT field with hyprlang grammar --
-- "active inactive fullscreen", the last two optional. There is no
-- opacity_inactive field, a bare number per state is not accepted, and
-- neither is a table { active =, inactive = }: the parser rejects all three
-- with "field 'opacity': string type requires a string".
--
-- Worse: `hyprctl reload` answers "ok" anyway and the rule is silently
-- dropped. The error only shows through `hyprctl configerrors` and in the
-- red banner in the corner. If you touch this, check with configerrors, not
-- with the exit code.
hl.window_rule({
    name  = "float-nautilus",
    match = { class = "^org\\.gnome\\.Nautilus$" },

    float  = true,
    size   = "1400 850",
    center = true,

    opacity = "0.82 0.74",
})

-- Loupe (images) and Celluloid (video) replaced gwenview and haruna. The
-- reason was the same one that pushed out Dolphin: both linked
-- libKF6ColorScheme, which forces BreezeDark on the app over the platform
-- theme, so they stayed grey while the rest of the desktop followed the
-- wallpaper.
--
-- Both are GTK4/libadwaita, meaning they read ~/.config/gtk-4.0/gtk.css just
-- like Nautilus and need no new template.
--
-- NO opacity here, unlike Nautilus, and that is deliberate: opacity in
-- Hyprland affects the whole window, content included. In an image viewer
-- and a media player that means blending the wallpaper into the picture you
-- are looking at -- goodbye blacks and any colour judgement. The glass is
-- for the chrome, not for the content.
hl.window_rule({
    name  = "float-loupe",
    match = { class = "^org\\.gnome\\.Loupe$" },

    float  = true,
    size   = "1400 850",
    center = true,
})

hl.window_rule({
    name  = "float-celluloid",
    match = { class = "^io\\.github\\.celluloid_player\\.Celluloid$" },

    float  = true,
    size   = "1280 720",   -- 16:9, so it does not come up letterboxed
    center = true,
})

-- zathura, the PDF reader.
--
-- Fixed "size" with A4 portrait proportions (850/1180 = 0.72, A4 is 0.707).
-- Measured: zathura does NOT request a size matching the document. With an
-- A4 portrait (ratio 0.71) it opens at 1252x952 and with a landscape one
-- (1.41) at 804x617 -- both windows land at ratio ~1.30, unrelated to the
-- page. So without a fixed size you get a landscape window for a portrait
-- document and wasted background on the sides.
--
-- Hyprland cannot measure the content either: it only sees what the window
-- asks for. Fitting it properly would need reading the page dimensions with
-- pdfinfo before opening and resizing afterwards.
--
-- 1180 of height fits DP-3 (1440) leaving room for waybar.
hl.window_rule({
    name  = "float-zathura",
    match = { class = "^org\\.pwmt\\.zathura$" },

    float  = true,
    size   = "850 1180",
    center = true,
})

-- satty, the annotation editor that SUPER+SHIFT+S pipes the screenshot into
-- (see the screenshot section above).
--
-- No "size" on purpose: the window fits the screenshot, and forcing a fixed
-- measure would distort the canvas depending on whether you grabbed a small
-- region or a whole monitor.
--
-- But "max_size" IS needed: satty asks for a window the size of the image,
-- so capturing a whole monitor (or opening a large image) pushes it off
-- screen and the buttons at the bottom end up out of reach. The cap fits
-- DP-3 leaving room for waybar.
hl.window_rule({
    name  = "float-satty",
    match = { class = "^com\\.gabm\\.satty$" },

    float    = true,
    max_size = "2400 1300",
    center   = true,
})


---------------
---- GAMING ----
---------------
-- Render, environment and window rules for games.
-- See ~/.config/hypr/gaming.lua
require("gaming")
