
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Identificamos los monitores por descripcion (marca + modelo + serie), no por
-- el nombre del conector (DP-4, HDMI-A-3...). Los nombres de conector los asigna
-- el kernel y CAMBIAN al cambiar de kernel: al pasar de linux-lts a linux
-- mainline, DP-4 paso a ser DP-3 y HDMI-A-3 paso a ser HDMI-A-1, y todas las
-- reglas de abajo dejaron de aplicarse en silencio (adios 165 Hz y rotacion).
-- La descripcion viene del EDID del monitor, asi que es estable.
-- Para verlas: hyprctl monitors all -j | grep description
MONITOR_PRINCIPAL = "desc:ASR PG32QF2B G5VL0A003533"
MONITOR_VERTICAL  = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GS27FA 24476B001914"

-- Principal: ASR PG32QF2B 1440p, a la derecha.
-- Y = 240 para centrarlo verticalmente contra el monitor vertical: (1920 - 1440) / 2
hl.monitor({
    output   = MONITOR_PRINCIPAL,
    mode     = "2560x1440@165",
    position = "1080x240",
    scale    = 1,
})

-- Secundario: Gigabyte GS27FA 1080p, rotado a vertical, a la izquierda.
-- transform = 3 -> 270 grados. Si la imagen sale al reves, cambia a 1 (90 grados).
-- Rotado ocupa 1080x1920, por eso el principal empieza en X = 1080.
hl.monitor({
    output    = MONITOR_VERTICAL,
    mode      = "1920x1080@165",
    position  = "0x0",
    scale     = 1,
    transform = 3,
})

-- Fallback para cualquier monitor no listado arriba
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"

-- Nautilus en vez de Dolphin. El motivo es el color: Dolphin ignoraba la
-- paleta del wallpaper hiciera lo que hiciera (la nota larga estaba en
-- matugen/config.toml), porque KF6 le imponia su BreezeDark interno.
-- Nautilus es GTK4/libadwaita y lee ~/.config/gtk-4.0/gtk.css, que ya lo
-- genera matugen, asi que entra en el sistema de acentos sin trabajo extra.
--
-- El otro gestor es ranger, que vive en la terminal y se lanza escribiendo
-- "ranger". No tiene bind a proposito: cuando lo quieres ya estas en kitty.
local fileManager = "nautilus"
local menu        = "wofi --show drun"

-- Menu de energia con confirmacion (SUPER + SHIFT + ESCAPE).
-- Ruta absoluta por coherencia con wallpaperSwitch.
local powerMenu   = os.getenv("HOME") .. "/.local/bin/hypr-powermenu"


------------------------------
---- PALETA DEL WALLPAPER ----
------------------------------

-- Ruta absoluta. Ya no es estrictamente necesaria (la seccion de
-- ENVIRONMENT VARIABLES agrega ~/.local/bin al PATH), pero se mantiene
-- porque el autostart corre en un momento delicado del arranque y esto
-- no puede fallar. Los scripts nuevos si pueden llamarse por nombre.
local wallpaperSwitch = os.getenv("HOME") .. "/.local/bin/wallpaper-switch"

-- colors.lua lo genera matugen cada vez que cambia el wallpaper.
-- Si no existe todavia (primer arranque, o matugen fallo) se usan
-- los colores originales, asi la config nunca se rompe.
local wallColors = { accent = "33ccff", accent2 = "00ff99" }

local ok, generated = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
if ok and type(generated) == "table" and generated.accent and generated.accent2 then
    wallColors = generated
end


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Sin esto los servicios de systemd --user (como wallpaper-rotate.timer)
    -- no ven WAYLAND_DISPLAY ni la firma de Hyprland, y no pueden hablar
    -- con el compositor. Tiene que ir primero.
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")

    -- Barra de estado. Config en ~/.config/waybar/
    hl.exec_cmd("waybar")

    -- Demonio de notificaciones
    hl.exec_cmd("dunst")

    -- Demonio de wallpapers + restaura el ultimo usado
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(wallpaperSwitch .. " reapply")

    -- Notificacion con caratula al cambiar de pista en el navegador
    -- (YouTube, YouTube Music). Va despues de dunst a proposito: si el
    -- demonio de notificaciones no esta levantado, la primera pista se
    -- pierde. Ver ~/.local/bin/mpris-notify.
    hl.exec_cmd("mpris-notify")

    -- En Wayland el portapapeles no se guarda en ningun sitio central: lo
    -- posee la aplicacion de origen. Al cerrarla, lo copiado se pierde.
    -- wl-clip-persist se queda con la propiedad para que sobreviva.
    -- Solo "regular": tocar tambien la seleccion primaria pelea con el
    -- clic central y provoca bucles de reescritura.
    hl.exec_cmd("wl-clip-persist --clipboard regular")

    -- Historial del portapapeles. Hacen falta dos vigilantes porque
    -- wl-paste --watch filtra por tipo MIME y uno solo dejaria fuera las
    -- imagenes (entre ellas las capturas de SUPER+S).
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Sin esto las apps Qt salen con la paleta gris de fabrica: no existe
-- ningun "tema Qt del sistema" que detectar en Hyprland, hay que
-- nombrarlo. Apunta a qt6ct, cuya paleta genera matugen desde el
-- wallpaper (~/.config/qt6ct/colors/matugen.conf).
--
-- OJO: es UNA sola variable para todas las versiones de Qt, y aqui
-- sirve solo a las Qt6. Una app Qt5 buscaria un plugin llamado "qt6ct"
-- en SU directorio (/usr/lib/qt/plugins/platformthemes/), no lo
-- encontraria y caeria al tema por defecto: paleta gris, y metrica de
-- fuente por defecto que le infla los tooltips y los menus.
--
-- Para arreglar una Qt5 harian falta qt5ct y un .desktop propio que le
-- sobrescriba la variable solo a ella. Comprobar antes con
-- `ldd $(which la-app) | grep libQt` de que version es.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Hyprland arranca con un PATH minimo que no incluye ~/.local/bin, asi
-- que cualquier script propio invocado por nombre falla en silencio.
-- Se evalua al cargar la config, tomando el PATH real del compositor.
hl.env("PATH", os.getenv("HOME") .. "/.local/bin:" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin"))

-- Sin esto, el dialogo "Abrir con" de Dolphin sale vacio. KService
-- construye su arbol de aplicaciones a partir de
-- /etc/xdg/menus/$XDG_MENU_PREFIX + applications.menu. Hyprland fija
-- el prefijo a "hyprland-", pero ese fichero no lo crea nadie: el
-- applications.menu clasico lo traia Plasma, que aqui no esta.
-- archlinux-xdg-menu instala arch-applications.menu, asi que hay que
-- apuntar el prefijo ahi.
--
-- OJO: al cambiar esto hay que regenerar la cache con
-- `kbuildsycoca6 --noincremental`, no basta con hyprctl reload.
hl.env("XDG_MENU_PREFIX", "arch-")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border = {
                colors = {
                    "rgba(" .. wallColors.accent  .. "ee)",
                    "rgba(" .. wallColors.accent2 .. "ee)",
                },
                angle = 45,
            },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        -- Efecto "glass": el blur lo aplica Hyprland detras de cualquier
        -- ventana transparente (kitty va a background_opacity 0.70).
        --
        --   size   = radio del desenfoque. Sube = mas difuso.
        --   passes = cuantas veces se repite. Es lo que convierte un
        --            velo tenue en cristal esmerilado de verdad.
        --            Mas de 4 casi no se nota y cuesta GPU.
        blur = {
            enabled = true,
            size    = 8,
            passes  = 3,

            -- Grano sutil: rompe el "banding" (escalones de color) que
            -- deja el blur sobre degradados del wallpaper.
            noise = 0.0117,

            -- Oscurece y baja el contraste de lo que hay detras, para
            -- que el texto claro de la terminal siga legible sobre
            -- wallpapers brillantes.
            contrast   = 0.9,
            brightness = 0.8,

            -- Satura los colores del fondo desenfocado (estilo macOS).
            vibrancy          = 0.1696,
            vibrancy_darkness = 0.0,

            -- Blur tambien en menus contextuales y popups.
            popups       = true,
            popups_ignorealpha = 0.2,

            -- xray = true difumina solo el wallpaper, ignorando las
            -- ventanas que haya debajo. Mas limpio y mas barato, pero
            -- pierdes la sensacion de capas apiladas. Pruebalo si tu
            -- GPU sufre con passes = 3.
            xray = false,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + W", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
-- Menu de energia (salir / reiniciar / apagar) con confirmacion.
-- Antes esto era SUPER + M sin ninguna proteccion y cerraba la sesion
-- al instante; demasiado facil de pulsar por accidente. Ahora pide
-- SHIFT + ESCAPE y ademas hay que elegir en el menu, donde "Cancelar"
-- viene preseleccionado. El script vive en ~/.local/bin/hypr-powermenu.
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd(powerMenu))

-- SUPER + M estuvo libre a proposito una temporada; ahora lo ocupa el
-- workspace especial magic, mas abajo, que cedio la S a las capturas.
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
-- Alternar flotante. Estuvo en SUPER+V, que era el bind de ejemplo de
-- Hyprland, pero esa tecla se cedio al historial del portapapeles: V de
-- "pegar" se usa mucho mas a menudo que flotar una ventana. T viene de
-- togglefloating, el nombre real del dispatcher.
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
-- Anclar: la ventana se queda visible en todos los workspaces de SU monitor,
-- en la misma posicion. SHIFT + T por continuidad con el flotante de arriba.
-- OJO: pin solo actua sobre ventanas flotantes, asi que el orden es
-- SUPER+T y luego SUPER+SHIFT+T. Y es por monitor: no cruza al otro.
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.pin())
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Workspace especial (scratchpad). Vivia en SUPER+S, pero esa tecla se
-- cedio entera a las capturas de pantalla, que se usan mucho mas a
-- menudo y donde SUPER+SHIFT+S es el gesto que ya tiene todo el mundo
-- en los dedos. M estaba reservada sin usar, asi que se muda aqui.
hl.bind(mainMod .. " + M",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:magic" }))

-- Wallpapers: SUPER+SHIFT+W pasa al siguiente, SUPER+SHIFT+A elige al azar.
-- Cada cambio regenera la paleta de acentos (waybar, kitty, bordes, dunst).
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(wallpaperSwitch .. " next"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(wallpaperSwitch .. " random"))

-- Capturas de pantalla: hyprshot (envoltorio sobre grim/slurp que ademas
-- pregunta a hyprctl por la geometria de ventanas y monitores) y satty
-- para anotar. Toda la familia SUPER+S es para esto; el workspace
-- especial magic se mudo a SUPER+M para dejarla libre.
--
-- -z congela la imagen mientras seleccionas la region. Sin eso no se
-- pueden capturar menus desplegables ni tooltips: desaparecen en cuanto
-- mueves el raton para arrastrar la seleccion. Necesita hyprpicker.
--
-- SUPER+S a secas solo copia al portapapeles y no toca el disco, que es
-- el caso habitual (pegar en el navegador o en Discord). Las variantes
-- que si escriben fichero van a ~/Pictures via XDG_PICTURES_DIR.
-- satty interpreta el nombre de salida con patrones strftime, asi que no
-- hace falta un $(date) por shell ni preocuparse por el escapado.
local sattyPipe = "satty --filename - --copy-command wl-copy --early-exit"
    .. " --output-filename " .. os.getenv("HOME") .. "/Pictures/satty-%Y%m%d-%H%M%S.png"

hl.bind(mainMod .. " + S",         hl.dsp.exec_cmd("hyprshot -m region -z --clipboard-only"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region -z --raw | " .. sattyPipe))
-- Los modos de hyprshot se combinan: "window" y "output" a secas abren un
-- selector para clicar la ventana o el monitor, que aqui sobra. Anadir
-- "active" hace que cojan directamente la ventana enfocada o el monitor
-- donde esta el raton, sin interaccion. Por eso tampoco llevan -z.
hl.bind(mainMod .. " + CTRL + S",  hl.dsp.exec_cmd("hyprshot -m window -m active"))
hl.bind(mainMod .. " + ALT + S",   hl.dsp.exec_cmd("hyprshot -m output -m active"))

-- Historial del portapapeles (cliphist), reusando wofi en modo dmenu, que
-- es el mismo lanzador de SUPER+SPACE. Se queda con SUPER+V a secas por
-- cercania con el Ctrl+V de toda la vida; el flotante que vivia aqui se
-- mudo a SUPER+T.
--
-- "decode" es imprescindible: cliphist list emite un id numerico y una
-- vista previa recortada, no el contenido. Sin decode pegarias el resumen.
-- Para vaciarlo: cliphist wipe
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(
    "cliphist list | wofi --dmenu --prompt Portapapeles | cliphist decode | wl-copy"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
-- -l 1.5 permite sobreamplificar hasta 150% (igual que max-volume en waybar)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Blur para waybar: la barra es semitransparente en el CSS,
-- pero el desenfoque real lo aplica Hyprland sobre la capa.
-- OJO: el namespace de la capa es el campo "name" de cada barra en
-- config.jsonc (no "waybar"). Si renombras una barra, actualiza esto.
hl.layer_rule({
    name  = "blur-waybar",
    match = { namespace = "^(principal|vertical)$" },

    blur          = true,
    ignore_alpha  = 0.2,

    -- Los tooltips de la barra (el panel que sale al pasar el cursor
    -- sobre un modulo) son popups de esta capa, no capas propias.
    -- Sin esto quedan semitransparentes pero SIN desenfocar, que es
    -- justo lo que se ve "transparente" en vez de "glass".
    blur_popups = true,
})

-- Blur para wofi (SUPER + SPACE). Mismo caso que waybar: el fondo
-- semitransparente lo pone ~/.config/wofi/style.css, el desenfoque va aqui.
-- El namespace de la capa de wofi es literalmente "wofi".
hl.layer_rule({
    name  = "blur-wofi",
    match = { namespace = "^wofi$" },

    blur          = true,
    ignore_alpha  = 0.2,
    blur_popups   = true,
})

-- Blur para las notificaciones de dunst. El namespace de su capa es
-- "notifications" (no "dunst"), como reporta `hyprctl layers`.
-- La transparencia base la define ~/.config/matugen/templates/dunstrc.
hl.layer_rule({
    name  = "blur-dunst",
    match = { namespace = "^notifications$" },

    blur          = true,
    ignore_alpha  = 0.2,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Apps auxiliares fuera del tiling: se abren un rato y se cierran, y
-- tileadas reordenan el resto del workspace en cada apertura.
--
-- Las clases son las que reporta `hyprctl clients`, NO el
-- StartupWMClass del .desktop: las apps KDE usan el ID inverso
-- ("org.kde.*") y las dos cosas no siempre coinciden. Haruna es el
-- ejemplo: su .desktop declara StartupWMClass=haruna, pero la ventana
-- se registra como "org.kde.haruna".

-- Nautilus, el gestor de archivos grafico (SUPER + E).
--
-- La transparencia es la unica parte del look que NO sale de GTK:
-- libadwaita pinta su fondo opaco y no hay forma de pedirle un alpha
-- desde el CSS de usuario, asi que la pone el compositor. El blur no
-- hace falta declararlo -- decoration.blur ya esta activo globalmente y
-- Hyprland lo aplica detras de cualquier ventana translucida, igual que
-- con kitty.
--
-- OJO: opacity afecta a la ventana ENTERA, texto e iconos incluidos.
-- 0.82 es el punto donde se ve el cristal sin que los nombres de
-- archivo se peleen con el wallpaper. Si bajas mas, el texto de las
-- etiquetas empieza a perder contraste sobre imagenes con detalle
-- claro; el blur ya viene con brightness 0.8 para compensar, pero
-- tiene un limite.
--
-- Y OJO tambien con la SINTAXIS, que aqui no es la que uno esperaria de
-- una config en Lua: opacity es un campo de TEXTO con la gramatica de
-- hyprlang -- "activa inactiva pantalla_completa", los dos ultimos
-- opcionales. No existe ningun campo opacity_inactive, ni se acepta un
-- numero suelto para cada estado, ni una tabla { active =, inactive = }:
-- las tres formas las rechaza el parser con "field 'opacity': string
-- type requires a string".
--
-- Peor aun: `hyprctl reload` responde "ok" igualmente y la regla se
-- queda sin aplicar en silencio. El error solo sale por
-- `hyprctl configerrors` y en el banner rojo de la esquina. Si tocas
-- esto, comprueba con configerrors, no con el codigo de salida.
hl.window_rule({
    name  = "float-nautilus",
    match = { class = "^org\\.gnome\\.Nautilus$" },

    float  = true,
    size   = "1400 850",
    center = true,

    opacity = "0.82 0.74",
})

-- Loupe (imagenes) y Celluloid (video) sustituyeron a gwenview y haruna.
-- El motivo fue el mismo que echo a Dolphin: los dos enlazaban
-- libKF6ColorScheme, que le impone BreezeDark a la app por encima del
-- tema de plataforma, asi que se quedaban en gris mientras el resto del
-- escritorio seguia al wallpaper. (El comentario que habia aqui decia
-- que Haruna cogia el tema de qt6ct; era falso, y se comprobo con
-- `ldd $(which haruna) | grep KF6ColorScheme`.)
--
-- Los dos son GTK4/libadwaita, o sea que leen ~/.config/gtk-4.0/gtk.css
-- igual que Nautilus y no necesitan ni una plantilla nueva.
--
-- SIN opacity, a diferencia de Nautilus, y es deliberado: opacity en
-- Hyprland afecta a la ventana entera, contenido incluido. En un visor
-- de fotos y en un reproductor eso significa mezclar el wallpaper con
-- la imagen que estas mirando -- adios a los negros y a cualquier
-- juicio de color. El cristal se queda para el chrome, no para el
-- contenido.
hl.window_rule({
    name  = "float-loupe",
    match = { class = "^org\\.gnome\\.Loupe$" },

    float  = true,
    size   = "1400 850",
    center = true,
})

hl.window_rule({
    name  = "float-celluloid",
    match = { class = "^io\\.github\\.celluloid_player\\.Celluloid$" },

    float  = true,
    size   = "1280 720",   -- 16:9, para que no salga con letterbox de origen
    center = true,
})

-- zathura, el lector de PDF.
--
-- "size" fijo con proporcion A4 vertical (850/1180 = 0.72, A4 es 0.707).
-- Medido: zathura NO pide un tamano acorde al documento. Con un A4
-- vertical (ratio 0.71) abre a 1252x952 y con uno apaisado (1.41) a
-- 804x617 -- las dos ventanas salen a ratio ~1.30, sin relacion con la
-- pagina. Asi que si no se le fija medida, sale una ventana apaisada
-- para un documento vertical y sobra fondo a los lados.
--
-- Hyprland tampoco puede medir el contenido: solo ve lo que la ventana
-- pide. Para que se ajuste de verdad haria falta leer las dimensiones
-- con pdfinfo antes de abrir y redimensionar despues.
--
-- 1180 de alto cabe en DP-3 (1440) dejando sitio a waybar.
hl.window_rule({
    name  = "float-zathura",
    match = { class = "^org\\.pwmt\\.zathura$" },

    float  = true,
    size   = "850 1180",
    center = true,
})

-- satty, el editor de anotaciones al que SUPER+SHIFT+S le pasa la
-- captura por tuberia (ver la seccion de capturas mas arriba).
--
-- Sin "size" a proposito: la ventana se ajusta al tamano de la captura,
-- y forzarle una medida fija deformaria el lienzo segun recortes una
-- region pequena o un monitor entero.
--
-- Pero SI hace falta "max_size": satty pide una ventana del tamano de
-- la imagen, asi que al capturar un monitor entero (o abrir una imagen
-- grande) se sale de la pantalla y los botones de abajo quedan fuera
-- de alcance. El tope cabe en DP-3 dejando sitio para waybar.
hl.window_rule({
    name  = "float-satty",
    match = { class = "^com\\.gabm\\.satty$" },

    float    = true,
    max_size = "2400 1300",
    center   = true,
})


---------------
---- GAMING ----
---------------
-- Reglas de render, entorno y ventanas para juegos.
-- Ver ~/.config/hypr/gaming.lua
require("gaming")
