#
# ~/.zshrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ---- PATH (migrated from .bashrc) ----
# typeset -U avoids duplicate entries when re-sourcing
typeset -U path PATH
path=("$HOME/.local/bin" $path)
export PATH

# ---- Aliases (migrated from .bashrc) ----
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# ---- Modern tools (only if installed) ----
if command -v eza >/dev/null; then
  alias ls='eza --group-directories-first --icons=auto'
  alias ll='eza -l --group-directories-first --icons=auto --git'
  alias la='eza -la --group-directories-first --icons=auto --git'
  alias lt='eza --tree --level=2 --icons=auto'   # quick tree
fi

if command -v bat >/dev/null; then
  alias cat='bat --paging=never'   # plain cat, with colours
  alias catp='bat'                 # with pager: search with /, quit with q
  export BAT_THEME='ansi'          # honours the terminal colours
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# rg = ripgrep (fast grep, with colours); grep is left untouched
alias rgi='rg -i'

# ---- fastfetch ----
# neofetch has been archived since 2024 and is not installed, so the alias
# shadows no binary: it is muscle memory, not a replacement.
# The config is generated by matugen (templates/fastfetch-config.jsonc).
if command -v fastfetch >/dev/null; then
  alias neo='fastfetch'
  alias neofetch='fastfetch'
fi

# ---- Prompt: starship (config in ~/.config/starship.toml) ----
PS1='[%n@%m %1~]%# '   # fallback, if starship is unavailable
command -v starship >/dev/null && eval "$(starship init zsh)"

# ---- History ----
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS      # do not store consecutive duplicates
setopt HIST_IGNORE_SPACE     # ignore commands starting with a space
setopt SHARE_HISTORY         # share history across sessions
setopt APPEND_HISTORY

# ---- Completion ----
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'   # case-insensitive

# ---- Behaviour ----
setopt AUTO_CD               # type a directory name to cd into it
setopt INTERACTIVE_COMMENTS  # allow # comments in the shell

# ---- Keys (Home/End/Delete/history search) ----
bindkey -e
bindkey '^[[H'  beginning-of-line
bindkey '^[[F'  end-of-line
bindkey '^[[3~' delete-char
bindkey '^[[A'  history-search-backward
bindkey '^[[B'  history-search-forward

# ---- fzf: fuzzy search (only if installed) ----
# Goes AFTER compinit and `bindkey -e`: it registers completion and remaps
# Ctrl-R, Ctrl-T and Alt-C on the emacs keymap. None of them clash with the
# keys above.
#
# `fzf --zsh` is the official way since 0.48; it avoids depending on the
# /usr/share/fzf/ paths, which are an Arch packaging detail.
if command -v fzf >/dev/null; then
  eval "$(fzf --zsh)"

  # --color=16 forces the terminal's 16 ANSI colours instead of the
  # 256-colour palette fzf ships with. Same criterion as BAT_THEME='ansi'.
  export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --color=16'

  # fd as the engine: it honours .gitignore and stays out of .git/.
  # Hidden files ARE requested here (the opposite of bare `fd`), because to
  # pick a path in ~ what you want is precisely .config and .local.
  if command -v fd >/dev/null; then
    export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --exclude .git'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d --strip-cwd-prefix --hidden --exclude .git'
  fi
fi

# ---- zoxide: a cd that learns (only if installed) ----
# Defines `z` and `zi`. Without this eval the binary exists but `z` does
# not: it is a shell function, not an executable.
#
# No --cmd cd on purpose: replacing cd with something that guesses
# destinations is risky with AUTO_CD on. `cd` stays literal.
if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

# ---- Neovim as a vi/vim replacement ----
alias vi='nvim'
alias vim='nvim'
export EDITOR='nvim'
export VISUAL='nvim'

# ---- Greeting when opening a terminal ----
# Goes last so it prints after everything else. Costs ~7ms.
#
# Both guards matter:
#   -o interactive : do not fire it in script shells.
#   -t 1           : nor when the output is captured or redirected.
#                    Without this it dirties any `zsh -ic 'cmd' | ...`
#                    and the kitty logo leaks into the pipe.
if [[ -o interactive && -t 1 ]] && command -v fastfetch >/dev/null; then
  fastfetch
fi
