// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
// MICROPHONE - push to talk, and who is allowed to open it
// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
//
// THE COMPOSITOR GATES THE MICROPHONE BECAUSE DISCORD CANNOT. On Wayland a
// window that is not focused never sees the keyboard, so Discord's own
// push-to-talk shortcut simply does not fire while you are in a game -- which
// is the only moment it was ever wanted. The way round it is to leave Discord
// on voice activity, where it transmits whatever it hears, and take the
// microphone away from it underneath: closed by default, open for as long as
// a key is held.
//
// DISCORD'S OWN PUSH-TO-TALK MUST STAY UNBOUND. With both, it latches on and
// stays transmitting -- an XWayland bug that nothing on the compositor side
// undoes. One gate or the other, never two.
//
// WHY THE SHELL OWNS IT RATHER THAN wpctl. The obvious version of this is two
// keybinds running `wpctl set-mute`, and it works -- it is where this came
// from. What it cannot do is answer a question: the settings window has a
// switch for push-to-talk, and a switch has to know whether it is on and what
// happens when it is turned off. This process already holds the PipeWire node
// that the switch is about, so putting the two together costs nothing and
// removes a spawn from the press path.
//
// THE PRICE, written down because it is real: push-to-talk now needs the
// shell running. If it dies while the microphone is closed, the key stops
// opening it -- so XF86AudioMicMute stays bound in both compositor configs
// and is the way back out.
//
// WHAT IS NOT HERE: the binds. They belong to the compositor, they are
// generated by `desktop-tweak` from the `ptt` and `ptt-key` values, and this
// file never reads them. It is called; it does not listen.

pragma Singleton

import Quickshell
import Quickshell.Io
import Quickshell.Services.Pipewire
// For Component.onCompleted, which is an attached object and needs the module
// that defines it even though nothing here is a visual item.
import QtQml

Singleton {
    id: root

    // The default source, and its audio interface once PipeWire has bound it.
    // Both can be null -- at startup, and for as long as a machine has no
    // capture device at all -- so everything below checks rather than assumes.
    readonly property var source: Pipewire.defaultAudioSource
    readonly property var audio: root.source?.audio ?? null

    // THE NODE'S OWN `ready`, AND NOT JUST `audio !== null`. Measured, because
    // the shorter version looks right and silently loses the one write that
    // matters: `audio` becomes non-null as soon as the node object exists,
    // which is BEFORE PipeWire has bound it, and a mute written in that window
    // is dropped -- Quickshell logs "Tried to change mute state for a node
    // which is not bound" and does not retry. The local value even reads back
    // as muted for a moment, so nothing looks wrong until the bind lands a
    // quarter of a second later and the microphone is open again.
    //
    // That window is exactly session startup, which is the only moment this
    // file has to get right.
    readonly property bool ready: (root.source?.ready ?? false) && root.audio !== null

    readonly property bool isOpen: root.ready && !root.audio.muted

    // WHETHER PUSH-TO-TALK IS ACTUALLY IN FORCE, which is not the same
    // question as whether the switch is on. The tweak store is shared by every
    // compositor on the machine -- that is the whole point of it -- so a
    // machine that turned push-to-talk on under Hyprland carries `ptt=1` into
    // niri, where nothing can open the microphone again and the settings
    // section that would turn it off is not on the page. Without this, logging
    // into the other compositor would mean a microphone muted on every reload
    // by a switch that cannot be reached.
    readonly property bool gated: Config.pushToTalk && Compositor.can("pushToTalk")

    // Read by shell.qml to bring this singleton into existence at startup.
    // Nothing else asks for it until a key is pressed, and by then the
    // microphone should already have been closed -- see the note there.
    readonly property bool armed: true

    function open(): void {
        if (root.ready)
            root.audio.muted = false;
    }

    function close(): void {
        if (root.ready)
            root.audio.muted = true;
    }

    function toggle(): void {
        if (root.isOpen)
            root.close();
        else
            root.open();
    }

    // Close it if push-to-talk is in force, and do nothing at all if it is not.
    //
    // THE ASYMMETRY IS THE POINT. This runs when the default source changes,
    // which includes a headset being plugged in, and the version that also
    // opened the microphone when push-to-talk was off would mean plugging in a
    // headset unmutes you. Closing an already closed microphone costs nothing;
    // opening one nobody asked to open is how a mute stops being trustworthy.
    function closeIfGated(): void {
        if (root.gated)
            root.close();
    }

    // Both the first source of the session and every one after it. A new
    // default while push-to-talk is on has to be closed too, or changing
    // microphone would be a way to end up transmitting without noticing.
    onReadyChanged: root.closeIfGated()

    // The same thing for the case where PipeWire was already bound before this
    // singleton existed, which is most reloads: `ready` never changes, so the
    // handler above never runs.
    Component.onCompleted: root.closeIfGated()

    // Turning push-to-talk ON closes the microphone -- that is what it means.
    // Turning it OFF opens it again, and that half is not symmetry for its own
    // sake: the binds go away with the switch, so leaving the microphone
    // closed would leave it closed with nothing left to open it.
    //
    // ON `gated` RATHER THAN ON THE SWITCH, so that the compositor becoming
    // known counts as a change too: `Compositor.can` answers false for the
    // moment before the backend has loaded, and a session that starts with
    // push-to-talk on reaches its real answer a tick later.
    onGatedChanged: {
        if (root.gated)
            root.close();
        else
            root.open();
    }

    // Called by the compositor, once on press and once on release.
    //
    // NOT GATED ON Config.pushToTalk. These are the microphone's controls, not
    // push-to-talk's: `qs ipc call mic toggle` is a working mute from any
    // terminal, and the day niri can run something on key release, whatever
    // ends up delivering that release calls exactly these.
    IpcHandler {
        target: "mic"

        function open(): void {
            root.open();
        }

        function close(): void {
            root.close();
        }

        function toggle(): void {
            root.toggle();
        }

        function status(): string {
            if (!root.ready)
                return "no microphone";
            return `${root.isOpen ? "open" : "closed"}, push-to-talk ${Config.pushToTalk ? "on" : "off"}`;
        }
    }

    // Without this PipeWire never binds the node and `audio` stays null, so
    // every call above would quietly do nothing. See the same tracker in
    // AudioPage.qml -- the binding is lazy and asking for a property is not
    // what triggers it.
    PwObjectTracker {
        objects: [Pipewire.defaultAudioSource]
    }
}
